server:
  port: 8080

spring:
  application:
    name: hospice-pricer-api

hospice:
  data:
    cbsa-file: classpath:data/CBSA2021
    msa-file: classpath:data/MSAFILE
    provider-file: classpath:data/PROVFILE
  rates:
    base-path: classpath:rates/
